### ISSUE TITLE
Segmentation fault (core dumped) in ubuntu16.04.

### ISSUE THREAD

**Issue by songjiaxina** [NathanUA/ground-truth-labeling#3]
the pre-built can not run in my ubunru. It shows Segmentation fault. Is there some way to build from sources?

**Comment by xuebinqin** [comment]
Sorry about the problem.

bylabel: $(objRRC)
	$(lnk) $(dbg) -o bylabel $(objRRC) -L lib -Wl,-rpath,'$$ORIGIN/lib' `pkg-config --libs opencv` EDLib.a EDLinesLib.a

Please try to replace the above lines  in the Makefile by follows:

bylabel: $(objRRC)
	$(lnk) $(dbg) -o bylabel $(objRRC) `pkg-config --libs opencv` EDLib.a EDLinesLib.a

And then compile the project by "make".

Pls make sure that your OpenCV version >=2.4.9 and the QT was enabled when installing the opencv. Otherwise the zoom in/out won't work.

**Comment by songjiaxina** [comment]
OK I will have a try. Thanks!
